version: "3"

services:
  web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/app/
    depends_on:
      - php
      - db

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/app/

  db:
    image: postgres:13.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=wdpaidb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password1234
